### PR TITLE
Update download script, use v0.13.2.1-litecore-rc2

### PR DESCRIPTION
**Pull request by ultragtx**

### CODE REVIEW

**Comment by karelbilek** [comment]
great, I just wanted to make this PR :D

**Comment by karelbilek** [comment]
ping me when it's published on npm, thanks, I think this will finally make litecore+segwit to work from npm directly :pray:

**Comment by losh11** [comment]
@runn1ng I was quite busy so didn't get to publish everything. I'll try my best to do that tonight. But updating the live instance of Inisight will probably be done tomorrow.

**Comment by karelbilek** [comment]
Thanks

We have our own instances :) just having it on npm is enough. Thanks a lot

**Pull request merged**
